version: '3.8'

services:
  postgres:
    image: postgres:16.4
    restart: always
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow_user
      POSTGRES_PASSWORD: airflow_pass
    volumes:
      - /opt/postgres/:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

# psql -U airflow_user
# \c airflow_db
# \l
# \dt
